name: 'az test'
on:
  workflow_dispatch:

jobs:
  build:
    name: 
    runs-on: ubuntu-latest

    steps:
    - name: Azure CLI script file
      uses: azure/cli@v2
      with:
        azcliversion: 2.56.0
        inlineScript: az --version